name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Jekyll site
      run: |
        # Create a Docker volume
        docker volume create jekyll-volume
        
        # Run the Jekyll build process
        docker run \
        --rm \
        --user root \
        -v jekyll-volume:/srv/jekyll \
        -v "${{ github.workspace }}/_site":/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "mkdir -p /srv/jekyll/.jekyll-cache && jekyll build --future"
