name: Auto-merge Stale Pull Requests

on:
  schedule:
  - cron: '*/5 * * * *'

jobs:
  merge_stale_prs:

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - name: Merge Stale PRs
      uses: pascalgn/automerge-action@v0.15.0
      with:
        merge-method: merge
        github-token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
