name: SLSA generic generator
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}

    steps:
      - uses: actions/checkout@v4

      # ========================================================
      #
      # Step 1: Build your artifacts.
      #
      # ========================================================
      - name: Build artifacts
        run: |
            # Check if the artifacts already exist and remove them to avoid conflicts
            [ -f artifact1 ] && rm artifact1
            [ -f artifact2 ] && rm artifact2

            # Create artifacts
            echo "artifact1" > artifact1
            echo "artifact2" > artifact2
        shell: bash

      # ========================================================
      #
      # Step 2: Add a step to generate the provenance subjects
      #
      # ========================================================
      - name: Generate subject for provenance
        id: hash
        run: |
          set -euo pipefail

          # Ensure artifacts are present
          if ! ls artifact* > /dev/null 2>&1; then
            echo "Error: No artifacts found for hashing." >&2
            exit 1
          fi

          # Generate the subjects (base64 encoded).
          files=$(ls artifact*)
          hashes=$(sha256sum $files | base64 -w0)

          # Write the output to an environment variable
          echo "digests=$hashes" >> $GITHUB_ENV
        shell: bash

  provenance:
    needs: [build]
    permissions:
      actions: read   # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    runs-on: ubuntu-latest
    steps:
      - name: Use SLSA GitHub Generator
        uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.4.0
        with:
          base64-subjects: ${{ env.digests }}  # Reference the environment variable
          upload-assets: true # Optional: Upload to a new release
